<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container452jgK7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container452jgK7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container452jgK7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container452jgK7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container452jgK7\App_KernelDevDebugContainer([
    'container.build_hash' => '452jgK7',
    'container.build_id' => '86bf731d',
    'container.build_time' => 1626727174,
], __DIR__.\DIRECTORY_SEPARATOR.'Container452jgK7');
