<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTueixaR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTueixaR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTueixaR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTueixaR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTueixaR\App_KernelDevDebugContainer([
    'container.build_hash' => 'TueixaR',
    'container.build_id' => '15030bf4',
    'container.build_time' => 1626620816,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTueixaR');
